### ISSUE TITLE
Navigation bar should not need to be scrolled

### ISSUE THREAD

**Issue by Ede123** [jsleroy/compare-plugin#20]
In the current development version of the compare plugin (I tested 129cfb9fa71f7ed9bb7f40fc04464f1df4adbc8a) the navigation bar was redesigned to be scrollable.

While this makes it a lot easier to locate the exact position of changes, it makes it impossible to quickly check (i.e. with one glance) where in the file changes were applied.

Personally I strongly prefer the previous behavior, where the navigation bar was only rescaled to fit the window height. This behavior should be brought back at least as an option.

**Comment by pnedev** [comment]
In the previous implementation it was possible some diffs not to be shown in NavBar due to the re-scaling. This is potentially dangerous as you rely on your first glance to get an idea of how many changes are there, where they are, etc. and if some are not shown you might overlook something important.
I'll think about what can be done. Meanwhile you can revert to an earlier state.

**Comment by Ede123** [comment]
Thanks!

Wouldn't it be possible to have every change at least 1px in height?
Only question would be how to handle overlapping changes that would overlap it the navbar then (e.g. a changed line next to a removed line)

**Comment by xylographe** [comment]
> how to handle overlapping changes

Perhaps, show the one with the highest priority? (from low to high: moved, changed, removed)

**Comment by pnedev** [comment]
I've added a setting making NavBar compact. Please delete your old _Compare.ini_ file when you update to the latest code snapshot.

**Comment by Ede123** [comment]
Great, thanks!
Seems to work fine on first look.
