### ISSUE TITLE
Shortcut key change conflict

### ISSUE THREAD

**Issue by norouzima** [jsleroy/compare-plugin#63]
I downloaded the latest version of Notepad++ (7.3.2) and Compare plugin (2.0.0). I noticed that the shortcut keys are changed (like instead of ALT+D I have to do CTRL+ALT+C) I also noticed that CTRL+ALT+SHIFT+X that is supposed to clear all compares is a reserved shortcut for Notepad++ (RUN -> Launch in FireFox). Now the question is, is there a way to customize the shortcut keys? and if yes, How?

**Comment by Yaron10** [comment]
Hello @norouzima,

The old `ALT+D` has been removed in order to avoid conflict with Window convention of `Alt+LETTER` opening the menu.

You can restore that (or choosing any other combination) via NPP Settings -> Shortcut Mapper.
And you're right: `CTRL+ALT+SHIFT+X` is used by NPP.
Thank you.

Hello Pavel,

How about replacing the "X" in both commands with "0" (zero)?
I haven't tried all possible other options but there are not many. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello @norouzima ,

Yaron has explained the things well - you can change the plugin shortcuts from _N++ Settings -> Shortcut Mapper -> Plugin Commands tab_ - locate there the command you'd like to assign different shortcut to.

Hello @Yaron10 ,

Thank you for the support.

> How about replacing the "X" in both commands with "0" (zero)?

I would really like to leave the things as they are now regarding the shortcuts. Because you are right - It is very hard to find a suitable / meaningful one. And there are always possibilities for conflicts, you cannot avoid all of them (N++ to Plugin conflict, Plugin to Plugin conflict). Everyone can freely change the predefined shortcuts to his / her liking so that's no big deal. I didn't set predefined shortcuts in NppGTags plugin exactly in order to avoid such situations.
Anyway, the users are getting used to the predefined CP shortcuts and constantly changing them actually causes more confusion - IOW - the Firefox shortcut conflict is the lesser evil. Of course I might be wrong :).
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

I suppose we have both modified shortcts.xml.
Providing a shortcut which doesn't work with the default NPP files might slightly tarnish the "Pavel Nedev" brand.
I wouldn't let that happen! :)

The shortcut for "Clear Active" can remain as it is.
And only `Ctrl+Shift+Alt+X` should be changed.
What do you think?

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

> Providing a shortcut which doesn't work with the default NPP files might slightly tarnish the "Pavel Nedev" brand.
I wouldn't let that happen! :)

Very well then :)

What about removing totally the _Clear All Compares_ shortcut? This command is rarely used actually (at least that's what I think) and in the rare case when someone needs it he / she can access it through the menu (or configure his / hers custom shortcut). This way we'll avoid possible conflicts and will not "pollute" the N++ shortcut space with actually unnecessary entries.
Thanks.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

> What about removing totally the Clear All Compares shortcut?

Great. "Pavel Nedev" has done it again. :)

Thank you.
BR

**Comment by pnedev** [comment]
Hello Yaron,

The predefined _Clear All Compares_ shortcut is removed, thanks.

@norouzima ,

As there is no feedback from you I consider this issue as closed.

BR

**Comment by Yaron10** [comment]
Hello Pavel,

Great. Thank you.

BR

**Comment by l3ender** [comment]
I think it might be helpful to have the release notes indicate the change of keyboard shortcuts and how to change shortcuts if desired. It took me a bit to realize that the plugin changed they shortcuts because there was no indication in the notes.

Thank you for the explanation and the work on this great plugin. I use it daily.

**Comment by Yaron10** [comment]
Hello @l3ender,

Pavel will add a user-guide to the next version.
The shortcuts are mentioned there but, you're right, it would be good to include this point in the release notes as well.

Thank you.

Best regards.

**Comment by pnedev** [comment]
Hello @l3ender ,

That's a good point, thanks.

Thanks @Yaron10 .

BR
