### ISSUE TITLE
Keyboard Shortcut problem

### ISSUE THREAD

**Issue by Laku83** [jsleroy/compare-plugin#69]
Hello,

in the last version of the plugin the new keyboard shortcut (Ctrl+Alt+C) is causing my OS ( Windows 7 and 10) to open the shutdown dialog after closing all my opened application, while the old combination (Alt+D) was working fine.
Is possible to have an option to set the shortcuts?

**Comment by Yaron10** [comment]
Hello @Laku83,

"Ctrl+Alt+C" is not a standard Windows shortcut for opening the shutdown dialog, is it?

Anyway, the old "Alt+D" has been removed in order to avoid conflict with Windows convention of Alt+LETTER opening the menu.

You can restore that (or choose any other combination) via NPP Settings -> Shortcut Mapper -> Plugin Commands.  

See https://github.com/jsleroy/compare-plugin/issues/63.

Best regards.
