### ISSUE TITLE
Request: Align windows vertically

### ISSUE THREAD

**Issue by itschytoo** [jsleroy/compare-plugin#71]
Hi.

I would really like if both windows could (optionally) be aligned when the space above them is different (due to number of tabs).

![clipboard01](https://cloud.githubusercontent.com/assets/2195559/24714326/7c377ae2-1a28-11e7-972e-360f1939a06b.png)

**Comment by pnedev** [comment]
Hello,

Yes, that was already reported here https://github.com/pnedev/compare-plugin/issues/105 and fixed after https://github.com/pnedev/compare-plugin/commit/bf46ed1858a75c19057f93aaaccd6c66b6b1c319.

The corresponding binaries are

- x64:  https://ci.appveyor.com/api/buildjobs/76labjggl914ffdt/artifacts/ComparePlugin.dll
- x86:  https://ci.appveyor.com/api/buildjobs/p5vsue8bqv0u4dvw/artifacts/ComparePlugin.dll

I won't be actively supporting / answering issues here. If you need help please write on my Compare Plugin clone page - https://github.com/pnedev/compare-plugin.

BR

**Comment by itschytoo** [comment]
Hi Pavel.

Sorry, I am confused.
I use the version 2.0 from plugin manager, which should be from the jsleroy-repository. According to the changelog it should have the fix you mentioned but doesn't.

Do I have to manually download and install the version from your repository?

Thanx,

Gerrit



Pavel Nedev schrieb am 06.04.2017 09:46:

**Comment by pnedev** [comment]
Hi @itschytoo ,

Long story-short, I continued CP development from where it stopped and I'm doing it in my project's clone.
The latest version 2.0 is from my repository but jsleroy-repository is synced to that (as code). Unfortunately I didn't have enough rights to make auto-deployment work with my user credentials on jsleroy repo, so the binary 2.0 is actually from my repo.

Version 2.0 doesn't have the change we are talking about - it was reported and fixed later.
You'll need to manually download the binary (dll) corresponding to your platform from the links I have provided in my previous post and manually replace your current ComparePlugin.dll in your Notepad++ install location plugins sub-folder. This is a development version binary that is fully working but has some new features (including the fix for your issue). The new development has diverged (and will further diverge) from jsleroy repo and will be available only in my repo. When I've finished with all the changes I've planned to do I'll officially release the next CP version but unless you are willing to wait for that to happen you can use the development binaries.

BR

**Comment by itschytoo** [comment]
Perfect.

Thank you for that explanation!

Greetings,
Gerrit


Pavel Nedev schrieb am 06.04.2017 11:37:
