### ISSUE TITLE
'Synchronize Vertical Scrolling' Cannot be disabled!

### ISSUE THREAD

**Issue by TheDemystifier** [jsleroy/compare-plugin#80]
A [video](https://youtu.be/MI0Kl-D4n80) says a thousand words! Notice how the Horizontal scrolling works as expected while the vertical scrolling is not!

NotePad++ Debug Info : 
Notepad++ v7.4.2   (32-bit)
Build time : Jun 18 2017 - 23:34:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck2.dll Explorer.dll mimeTools.dll PluginManager.dll

**Comment by pnedev** [comment]
That is the normal behavior of the Compare mode.
When you compare two files the Compare plugin takes care of the appropriate vertical scroll synchronization between the files. That's because the Notepad++ vertical scroll is not 'content-aware' sort of speak. And Compare plugin actually aligns found differences so you can conveniently see them side by side as if linked. This compare mode vertical sync cannot be turned off. You need to clear the current compare to do that.
